config/routes.rb
Rails.application.routes.draw do
 # get 'home/index'
  get 'home/about'
  get 'home/locationdata'
  get 'home/motiondata'
  get 'home/videodata'
  get 'home/audiodata'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about 
  end
  def audiodata 
  end
  def motiondata
  end
  def videodata 
  end
  def locationdata 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
CopCam Dashboard </br><br/>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to "CopCam Dashboard" , root_path, class: "navbar-brand" %>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-5 mb-lg-0">
        </li>
        <li class="nav-item">
        	<%= link_to "About Us", home_about_path, class: "nav-link" %>

        </li>
        <li class="nav-item">
          <%= link_to "Audio Data", home_audiodata_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Video Data", home_videodata_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Location Data", home_locationdata_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Motion Data", home_motiondata_path, class: "nav-link" %>
        </li>
        


         
           
          </ul>
        
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About Us ...</h1>
<br/>
<br/>
<br/>
<br/>

<h1> This site web app was designed to allow users of the CopCam to interact with the data it collects.  </h1>

app/views/home/audiodata.html.erb
<h1> Audio Recording Data </h1>

<br/>
<br/>
<br/>
<br/>

<h1> Play Audio Recording  </h1>

app/views/home/index.html.erb
<h1>Home
<p>Hello World</h1></p>
<p>This is my first rails webpage!</h1></p>

app/views/home/locationdata.html.erb
<h1> Location Data ...</h1>
<br/>
<br/>
<br/>
<br/>

<h1> Map of vehicular travel.  </h1>

app/views/home/motiondata.html.erb
<h1> Motion Data</h1>
<br/>
<br/>
<br/>
<br/>

<h1> Speed Data </h1>

<button type="button" class="btn btn-primary btn-lg">Get Data</button>



<br/>
<br/>
<br/>
<br/>

<h1> Stop Data </h1>



<br/>
<br/>
<br/>
<br/>

<h1> What's the evidence that I was driving erratically? </h1>

app/views/home/videodata.html.erb
<h1> Video Footage </h1>

<br/>
<br/>
<br/>
<br/>

<h1> Enter data about the officer here: </h1>

<br/>
<br/>
<br/>
<br/>

<h1> Seat Belt Data </h1>

<br/>
<br/>
<br/>
<br/>

<h1> Was I on my phone?  </h1>

<br/>
<br/>
<br/>
<br/>

<h1> Auto Face Blurring  </h1>


<br/>
<br/>
<br/>
<br/>

<h1> Upload video to social media using our bot.  </h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>CopCam Webapp</title>
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
     <div class = "container">
       <br/>
       <%= yield %>
     </div>  
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>